### ISSUE TITLE
NO-IP LINK

### ISSUE THREAD

**Issue by Nour833** [D4rkS3c-Group/HiddenEyeReborn#3]
Hello 
Can you please add feature witch use the link of no-ip (dynamic  dns service ) witch is linked to localhost to make it easier to customize domain name  and maybe solve many other problems  like blocking urls and ngrok slow server .
This is one of my ideas I hope you can do it and thanks in advance <3

**Comment by sTiKyt** [comment]
You want to be able to use no-ip as tunelling option, right?

This no-ip? https://www.noip.com/

**Comment by Nour833** [comment]
> You want to be able to use no-ip as tunelling option, right?
> 
> This no-ip? https://www.noip.com/

Exactly to tunnel my public ip

**Comment by sTiKyt** [comment]
> > You want to be able to use no-ip as tunelling option, right?
> > This no-ip? https://www.noip.com/
> 
> Exactly to tunnel my public ip

Okay, i'll think about it after we restore bsic functionality of HiddenEye

**Comment by E1MWM13** [comment]
> > > You want to be able to use no-ip as tunelling option, right?
> > > This no-ip? https://www.noip.com/
> > 
> > 
> > Exactly to tunnel my public ip
> 
> Okay, i'll think about it after we restore basic functionality of HiddenEye

You still use pyngrok ?

**Comment by E1MWM13** [comment]
> > > You want to be able to use no-ip as tunelling option, right?
> > > This no-ip? https://www.noip.com/
> > 
> > 
> > Exactly to tunnel my public ip
> 
> Okay, i'll think about it after we restore basic functionality of HiddenEye

Pls make sure its work for Termux without root i am always waiting

**Comment by E1MWM13** [comment]
> > > You want to be able to use no-ip as tunelling option, right?
> > > This no-ip? https://www.noip.com/
> > 
> > 
> > Exactly to tunnel my public ip
> 
> Okay, i'll think about it after we restore basic functionality of HiddenEye

Dude, you gotta code this thing! Stop procrastinating you lazy bastard!

ops sorry dev haha just testing

**Comment by sTiKyt** [comment]
@E1MWM13 i got your messages but gonna delete those due to being offtopic, if you have any questions - you can visit our telegram. https://t.me/darksecofficial

**Comment by sTiKyt** [comment]
Found this [noipy](https://github.com/pv8/noipy) thing. Looks like it may be used to implement NO-IP support. Will look into it later.

**Comment by sTiKyt** [comment]
Closing here, track this issue in #85
