### ISSUE TITLE
[Development] Mirror system

### ISSUE THREAD

**Issue by sTiKyt** [D4rkS3c-Group/HiddenEyeReborn#61]
Templates won't be stored on git repository, to make sure we don't infringe copyright, what I'm proposing instead can be described in a couple of steps:

- Upload templates as archives to 3rd party file storage
- Add direct download links to text file for specific template, we can call it "template TXT"
- Upload those template TXTs  to 3rd party file storage
- Add links to template TXTs to "mirrorlist" file with md5 and sha256 hashes included per archive of specific version, e. g. "Github Template 0.3"
- Implement code to automatically:

     1. Fetch mirrorlists
     2. Parse them for links
     3. Fetch template TXTs
     4. Parse them for links
     5. Download latest version of template
     6. Verify it with hash
     7. If valid - move from temporary folder to main templates storage
     8. If invalid - delete and cleanup, throw an error and make sure to write it to debug logs
     
As per templates versioning, we can use creation date, e.g. "GitHub 23/08/2021"

**Comment by sTiKyt** [comment]
As per templates versioning, we can be using creating date, e.g. "Github 23/08/2021"

**Comment by Skjnior** [comment]
@sTiKyt Hum

**Comment by im2gm** [comment]
Can we chat privately on telegram

**Comment by medsdeb** [comment]
how

On Sep 18, 2021, at 03:10, im2gm ***@***.***> wrote:

﻿
Can we chat privately on telegram

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sTiKyt** [comment]
I'm closing all comments due to offtopic

**Comment by sTiKyt** [comment]
Reiterated upon this concept, closing the issue accordingly.
