### ISSUE TITLE
bazel/bravo/bravo.txtñ

### ISSUE THREAD

**Issue by jinalikerkuk** [D4rkS3c-Group/HiddenEyeReborn#89]
https://github.com/kujian/githubTrending/tree/master

**Comment by jinalikerkuk** [comment]
pip install hiddeneye-reborn

**Comment by Morsmalleo** [comment]
> pip install hiddeneye-reborn

Don't spam the issue section with BS Issues like this!!

**Comment by Morsmalleo** [comment]
> > pip install hiddeneye-reborn

What's so hard about describing your problem in detail?! Jesus Christ it's actually annoying!! I see this everywhere on GitHub even on my own repositories, I feel for other developers it happens to as well.

Either fill out the issue properly or don't bother trying to even use this tool until you know more about what you're doing!!!

**Comment by sTiKyt** [comment]
> https://github.com/kujian/githubTrending/tree/master
> 

I've got no idea what are you trying to say, and that link looks like a weird Chinese bot ad, I don't speak Chinese and this repo is in English

**Comment by sTiKyt** [comment]
Reported you just in case
